version: '3'

services:
  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/node-course
    depends_on:
      - database
    
  database:
    container_name: database
    image: mongo
    env_file:
      - .env.db
    ports:
      - 27017:27017
    volumes:
      - database-volume:/data/db

volumes:
  database-volume:
